export const dummyData = {
  '1': {
    companyLegalName: 'Alpha Tech Solutions',
    tin: '123-456-789',
    address_1: '123 Innovation Drive',
    address_2: 'Suite 200',
    email: 'info@alphatech.com',
    phone: '+1-555-123-4567',
    shortDescription: 'A leading provider of tech solutions.',
  },
  '2': {
    companyLegalName: 'Beta Logistics',
    tin: '987-654-321',
    address_1: '456 Supply Chain Road',
    address_2: null,
    email: 'contact@betalogistics.com',
    phone: '+1-555-987-6543',
    shortDescription: 'Reliable logistics and supply chain management.',
  },
  '3': {
    companyLegalName: 'Gamma Financial Group',
    tin: '555-333-111',
    address_1: '789 Finance Street',
    address_2: 'Floor 10',
    email: 'services@gammafinance.com',
    phone: '+1-555-555-1234',
    shortDescription: 'Financial advisory and investment services.',
  },
  '4': {
    companyLegalName: 'Delta Manufacturing Co.',
    tin: '222-333-444',
    address_1: '101 Industrial Avenue',
    address_2: null,
    email: 'sales@deltamfg.com',
    phone: '+1-555-222-3333',
    shortDescription: 'Custom manufacturing for industrial needs.',
  },
  '5': {
    companyLegalName: 'Epsilon Energy Ltd.',
    tin: '777-888-999',
    address_1: '205 Renewable Road',
    address_2: 'Suite 500',
    email: 'support@epsilonenergy.com',
    phone: '+1-555-777-8888',
    shortDescription: 'Sustainable energy solutions provider.',
  },
  '6': {
    companyLegalName: 'Zeta Pharmaceuticals',
    tin: '111-222-333',
    address_1: '909 Health Park',
    address_2: null,
    email: 'info@zetapharma.com',
    phone: '+1-555-111-2222',
    shortDescription: 'Innovative pharmaceutical products and research.',
  },
  '7': {
    companyLegalName: 'Eta Construction Inc.',
    tin: '444-555-666',
    address_1: "808 Builder's Lane",
    address_2: 'Unit 12A',
    email: 'contact@etaconstruction.com',
    phone: '+1-555-444-5555',
    shortDescription: 'Commercial and residential construction services.',
  },
  '8': {
    companyLegalName: 'Theta Digital Media',
    tin: '666-777-888',
    address_1: '456 Creative Blvd',
    address_2: 'Studio 7',
    email: 'hello@thetadigital.com',
    phone: '+1-555-666-7777',
    shortDescription: 'Digital marketing and creative solutions.',
  },
  '9': {
    companyLegalName: 'Iota Consulting Group',
    tin: '333-444-555',
    address_1: '321 Business Center',
    address_2: null,
    email: 'team@iotaconsulting.com',
    phone: '+1-555-333-4444',
    shortDescription: 'Business consulting and strategy planning.',
  },
  '10': {
    companyLegalName: 'Kappa IT Solutions',
    tin: '888-999-000',
    address_1: '654 Tech Valley',
    address_2: 'Building 3, Room 204',
    email: 'support@kappait.com',
    phone: '+1-555-888-9999',
    shortDescription: 'IT support and software development.',
  },
};
